version: "3.8"

services:
  database:
    image: mariadb:latest
    container_name: database
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secretadmin
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=secretadmin
      - INSTALL_SAKILA=1
  php-apache:
    container_name: php-apache
    build:
      context: ./php
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/laravel_docker
      - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - database
